package com.example.whereto;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.view.WindowManager;

import java.util.ArrayList;
import java.util.List;

public class MostViewedScreen extends AppCompatActivity {
    RecyclerView recycler;
    List<Model> modelList;
    RecyclerView.Adapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_most_viewed_screen);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);


        modelList = new ArrayList<>();
        recycler = findViewById(R.id.recyclerView);
        recycler.setHasFixedSize(true);
        recycler.setLayoutManager(new LinearLayoutManager(this));
        //call our items
        modelList.add(new Model(R.drawable.delhi,"Delhi","Delhi, India’s capital territory, is a massive metropolitan area in the country’s north.A symbol of the country’s rich past and thriving present, Delhi is a city where ancient and modern blend seamlessly together. It is a place that not only touches your pulse but even fastens it to a frenetic speed. Home to millions of dreams, the city takes on unprecedented responsibilities of realizing dreams bringing people closer and inspiring their thoughts.\n" +
                "Just a century ago, the British moved the seat of their empire from Kolkata to Delhi. And it has been the Capital of India ever since. Now a thriving, cosmopolitan metro, the city has much to celebrate as it has already reached the milestone of completing 100 years as a Capital. With a history that goes back many centuries, Delhi showcases an ancient culture and a rapidly modernising country. Dotted with monuments there is much to discover here. The seat of many powerful empires in the past, its long history can be traced in its many carefully-preserved monuments, ancient forts and tombs.\n" +
                "\n" +
                "All this is combined with the best features of a modern city such as a metro system, bustling markets and fabulous eating places. The past and the present meld seamlessly together, making centuries-old monuments a part of the city’s daily life. Delhi is very much a history’s child. The story of the city is as old as the epic Mahabharata, when the town was known as Indraprastha, where Pandavas used to live. Over the centuries, eight more cities came alive adjacent to Indraprastha: Lal Kot, Siri, Dinpanah, Quila Rai Pithora, Ferozabad, Jahanpanah, Tughlakabad and Shahjahanabad. Many empires rose to the heights of their power and were destroyed here. Among the prominent dynasties which made Delhi their capital were the Tughlaqs, the Khiljis and the Mughals.\n" +
                "\n" +
                " But the modern Delhi has a lot more to offer. Delhi has a modern, well-planned and extensive Metro network that connects all corners of Delhi; this network is still growing. New roadways and flyovershave improved connectivity, the latest of which is the Signature Bridge, an ambitious project of Delhi Tourism, which is under construction at Wazirabad – it promises to be a landmark. "));
        modelList.add(new Model(R.drawable.mumbai,"Mumbai","Mumbai (formerly called Bombay) is a densely populated city on India’s west coast. Mumbai, previously known as Bombay is one of the most populous and biggest cities of Maharashtra. Also the biggest metropolis of this state, Mumbai is also popular as the entertainment and financial capital. It is the largest city of India and fondly called as the city of dreams. It is a place filled with dreamers and people who work hard day and night to achieve their dreams. From struggling actors, laboureres, Bollywood stars to gangsters, Mumbai has a lot. A lot that can be written about and talked about! Mumbai is also home to one of the biggest slum area as well as home to the richest and thus it is only fair to describe Mumbai as a city for all. The majorsly spoken language is definitely Hindi , but this city has welcomed people from all faiths and religion warmly. If you want to know and experience diversity, visit Mumbai. This city also has its very own language that is the Bambaiiya Hindi. Known to be a city filled with warm and friendly people, we believe that anything written about Mumbai is never enough.\n" +
                "\n" +
                "If you are planning to visit Mumbai, trust us when we say it may look intimidating initially, but it is not. In fact it is one of the friendliest cities of India. The extreme energy and the fast paced life of the people here cannot be easily matched. The heart of Mumbai has some of the best and beautiful colonial architecture and if you venture out to the lesser known lanes, you will also come across several distinct bazaars, temples, fancy restaurants and a nightlife that is one of its kinds. Before Mumbai became the city hat it is now, it was a collection of seven islands which was eventually formed to form Bombay. It was given to the British as dowry to Charles II who married Catherine of Braganza. The island city that Mumbai is today is owing to these reclamation and these islands were home to several fishing colonies. The British made Mumbai an important port since it was already had a natural harbor but it rose to its richness during the American Civil War when cotton supplies were completely stopped from America to Britain. India made the most of this situation and it is said that traders earned approximately 80 million pounds which is a lot of money. This made way for Bombay’s very own merchant traders who were rich. As you walk around in the many lanes of South Bombay you will still get to witness the remnants of this city’s glorious past. Cotton factories and many buildings that are dilapidated are still to be seen scattered around many parts of Mumbai, especially South Mumbai. Apart from this, another every interesting par about this city is that in spite of the several unfortunate incidents and acts of terrorism this city has seen, it still moves on and lives with the same love for Mumbai."));
        modelList.add(new Model(R.drawable.bangalore,"Bengaluru","Bengaluru (also called Bangalore) is the capital of India's southern Karnataka state. Bengaluru is also known as the Silicon Valley of India. The city is known for its beautiful gardens and parks and is a fusion of ancient and modern times. The city is home to a large number of young migrants from across India which has resulted in it becoming a much sought after destination for international entertainment concerts The capital of Karnataka State, Bengaluru, also known as the 'City of Gardens', is one of the most attractive cities in India with its beautiful parks, avenues and impressive buildings. Historically known as Vengaluru, Bendakaluru (village of boiled beans) and as the anglicized Bangalore, Bengaluru has moved to be city that is cosmopolitan in nature and a nerve center of the Arts and Culture as well. The once-sedate cantonment settlement of the British has now spread way beyond the mud fort and the four towers constructed by Kempe Gowda in 1537. With its booming economy and racy lifestyle, the capital of Karnataka has metamorphosed from a sleepy Garden City into one of India's fastest growing, accommodating and cosmopolitan cities. Bengaluru is a city of contrasts, going by several other aliases: India's Silicon Valley, Pub City, Shopper's Paradise, Garden City, Air-conditioned City, Gourmet's Delight, Pub Hopper's Paradise, Pensioners Paradise, IT and BT City and Shopper's Hot Spot. Surrounded by weekend getaways, Bengaluru makes an ideal hub for visitors who want to travel to the many hill stations and coastal towns of South India."));
        modelList.add(new Model(R.drawable.chennai,"Chennai","Chennai, on the Bay of Bengal in eastern India, is the capital of the state of Tamil Nadu. Chennai or Madras as it was called before, on the Coromandel Coast, is the capital city of Tamil Nadu, a State of the Indian Sub continent. It is a major industrial, commercial, cultural, economic and educational centre of the Southern India. The Chennai District’s population is 46,81,087 [2011 census]. Chennai City is the sixth largest populated in Indian cities. It is known as the \"Detroit of India\" because many automobile industries are located here. The city also has a population of over 80,000 expatriates as per 2011 census.\nBeautiful Beaches, One day leisure outlets, Modern Sea Port and Airport, Long and beautiful Highways, Convenient multi-Transport system, Theme parks, Industrial cities, Hi –Tech software silicon valley parks, Sophisticated Multi Speciality Hospitals, World Class Universities, High Rise Business and Residential complexes are the present days outlook of the great Chennai, most sought after by the people of all walks of life from all parts of the world."));
        modelList.add(new Model(R.drawable.kochi,"Kochi","Kochi (also known as Cochin) is a city in southwest India's coastal Kerala state. Adorned by the enchanting charm of the Arabian Sea, Kochi or Cochin boasts of being one of the best tourist destinations in Kerala that is perfectly blended with an old world charm and the electrifying beauty of modern day world! Located within the Ernakulam district of God’s Own Country, this gorgeous city is also called the ‘Queen of the Arabian Sea’ and has been a centre of attraction since time immemorial!\n" +
                "\n" +
                "An important port city; in fact the most popular, in Kerala, Kochi showcases a mixed bag of culture. Once ruled by Portuguese, Dutch, and British, the city still echoes the essence and aura of these eras in livelier ways. Also, owing to its location along the shorelines of the Arabian Sea, it has been an important spice trade centre for countries like Syria, Arab, China, and several other Asian countries.\n" +
                "\n" +
                "Rated as one of the ’50 Greatest Places to Visit in a Lifetime’ by National Geographic Traveller Magazine, Kochi is truly is a melting point of history and culture. Though the city boasts of its cosmopolitan outlooks, it is still connected to its indigenous roots with its high cultural and traditional values. If you are planning for a Kerala trip, a visit to this promising port city is a must"));
        modelList.add(new Model(R.drawable.hyderabad,"Hyderabad","Hyderabad is the capital of southern India's Telangana state. A major center for the technology industry,Hyderabad is the capital of one of the most techno savvy state in India,Telangana. The previous name of this city was Bagyanagaram.This city is also called the ‘city of pearls’ because of the major dealing of pearls that is done from this part of the state. Hyderabad was founded in 1591 and planned as a grid with the Charminar at its centre. It has now grown well beyond the confines of the original walled city,to include a new town north of the Musi river, the Military Cantonment at Secunderabad and a burgeoning high-tech Estate, nicknamed “Cyberabad”."));
        modelList.add(new Model(R.drawable.goa,"Goa","Goa is a state in western India with coastlines stretching along the Arabian Sea."));

        //init the adapter with model list and context
        adapter = new CustomAdapter(modelList,getApplicationContext());
        //set the adapter into recyclerView
        recycler.setAdapter(adapter);
    }
}
